### ISSUE TITLE
Lessons out of order

### ISSUE THREAD

**Issue by Tcviles** [learn-co-curriculum/ruby-remembering-objects-readme#16]
I believe this remembering objects read me has information that would have been useful for the class variables and methods lab that is before this page. Just figured id put my 2 cents in! thanks!

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#17.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
