### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by curiositypaths** [learn-co-curriculum/ruby-remembering-objects-readme#17]
PROBLEM: Review lesson order and relationship to related lessons. See issue #16.
NOTIFY: @tcviles

PROBLEM: Review overlap between this lesson and https://github.com/learn-co-curriculum/ruby-class-variables-and-class-methods-readme. See issue #14 
NOTIFY: @gj 

PROBLEM: Lesson Placement. See issue #20 
NOTIFY: @helloamandamurphy

**Comment by sgharms** [comment]
We're preparing to push a new version of this module. We'll add lesson placement concerns as part of the deploy criteria there.
