### ISSUE TITLE
Lesson Placement

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/ruby-remembering-objects-readme#20]
Hey guys! This lesson would be extremely helpful to read before completing the Class Variables and Methods lab in the previous section. Consider moving it.

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#17. We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
