### ISSUE TITLE
Invalid variable name in example

### ISSUE THREAD

**Issue by eaylward8** [learn-co-curriculum/ruby-remembering-objects-readme#6]
There's a problem with the example that says, "With this code, we can create a new song like this:"

`99_problems = Song.new("99 Problems")`

The variable name can't start with a number.  It should be named something like `ninety_nine_problems`.

**Comment by AnnJohn** [comment]
thanks for raising this issue. will fix soon.

**Comment by eaylward8** [comment]
😉
